<?php

return [
    'all' => [
        "caseId",
        // "your_advocates[]",
        // "your_advocates[]",
        // "your_team[]",
        "timeLineId",
        "name",
        "case_number",
        "open_date",
        "close_date",
        "incident_date",
        "statute_of_limitations",
        "case_stage",
        "description",
        "fall_c_name",
        "fall_c_gender",
        "fall_c_marital_status",
        "fall_c_spouse_name",
        "fall_c_emergency_contact_name",
        "fall_c_emergency_contact_number",
        "fall_c_dob",
        "fall_c_social_security",
        "fall_c_address",
        "fall_c_phone",
        "fall_c_email",
        "fall_c_driver_license",
        "fall_c_id",
        "fall_tpi_name",
        "fall_tpi_phone",
        "fall_tpi_address",
        "fall_tpi_email",
        "fall_mi_name",
        "fall_mi_phone",
        "fall_mi_address",
        "fall_mi_email",
        "fall_ii_incident_date",
        "fall_ii_time",
        "fall_ii_location_of_incident",
        "fall_ii_address",
        "fall_ii_maps_link",
        "fall_ii_cause_incident",
        "fc_police_department",
        "fc_incident_report",
        "fall_ifp_company_name",
        "fall_ifp_insured_name",
        "fall_ifp_poilicy",
        "fall_ifp_member",
        "fall_ifp_claim",
        "fall_ifp_insurance_phone",
        "fall_ifp_adjuster_name",
        "fall_ifp_adjuster_email",
        "fall_ifp_adjuster_phone",
        "fall_ifp_adjuster_fax",
        "fall_ifp_adjuster_policy_limits",
        "fall_itp_company_name",
        "fall_itp_insured_name",
        "fall_itp_poilicy",
        "fall_itp_claim",
        "fall_itp_insurance_phone",
        "fall_itp_adjuster_name",
        "fall_itp_adjuster_email",
        "fall_itp_adjuster_phone",
        "fall_itp_adjuster_fax",
        "fall_itp_adjuster_policy_limits",
        // "witness[witness_name][]",
        // "witness[witness_email][]",
        // "witness[witness_phone][]",
        // "witness[witness_address][]",
        "fall_o_incident_report",
        "fall_o_opponent_counsel",
        "fall_o_name",
        "fall_o_phone",
        "fall_o_email",
        "fall_o_fax",
        "location_of_accident",
        "intersection",
        "coordinates",
        "case_manager",
        "file_location",
        "first_party_company_name",
        "first_party_policy_name",
        "first_party_insurance_phone_number",
        "first_party_name",
        "first_party_phone_number",
        "first_party_policy_limits",
        "first_insured_name",
        "first_party_claim_number",
        "first_party_adjuster",
        "first_party_email",
        "first_party_fax",
        "third_party_company_name",
        "third_party_policy_name",
        "third_party_insurance_phone_number",
        "third_party_name",
        "third_party_phone_number",
        "third_party_policy_limits",
        "third_insured_name",
        "third_party_claim_number",
        "third_party_adjuster",
        "third_party_email",
        "third_party_fax",
        "first_party_driver_name",
        "first_party_vehicle_model",
        "first_party_vehicle_make",
        "first_party_vehicle_license",
        "first_party_passenger_name",
        "emergency_name",
        "emergency_phone",
        "third_party_driver_name",
        "third_party_vehicle_year",
        "third_party_vehicle_model",
        "third_party_vehicle_make",
        "third_party_vehicle_license",
        "third_party_passenger_name",
        "police_report",
        "recorded_statement_description",
        "other_name",
        "other_phone_number",
        "other_email_address",
        "other_fax",
        // "opponents[opponents_name][]",
        // "opponents[opponents_email][]",
        // "opponents[opponents_phone][]",
        // "opponent_advocates[opp_advocates_name][]",
        // "opponent_advocates[opp_advocates_email][]",
        // "opponent_advocates[opp_advocates_phone][]"
    ],
    'fieldsToUpdate' => [
            'name','case_number',  'case_stage', 'description',
            'location_of_accident', 'statute_of_limitations', 'intersection', 'coordinates',
            'injury_type',  'case_manager', 'file_location',
            'first_party_company_name', 'first_party_policy_name', 'first_party_insurance_phone_number',
            'first_party_name', 'first_party_phone_number', 'first_party_policy_limits',
            'first_insured_name', 'first_party_claim_number', 'first_party_adjuster', 'first_party_email',
            'first_party_fax',
            'third_party_company_name', 'third_party_policy_name', 'third_party_insurance_phone_number',
            'third_party_name', 'third_party_phone_number', 'third_party_policy_limits',
            'third_insured_name', 'third_party_claim_number', 'third_party_adjuster', 'third_party_email',
            'third_party_fax',
            'first_party_driver_name',  'first_party_vehicle_model','first_party_passenger_name', 'first_party_vehicle_make',
            'first_party_vehicle_license', 
            'emergency_name', 'emergency_phone',
            'third_party_driver_name', 'third_party_vehicle_year', 'third_party_vehicle_model', 'third_party_passenger_name', 'third_party_vehicle_make',
            'third_party_vehicle_license',
            'police_report', 'recorded_statement', 'recorded_statement_description', 'other_name',
            'other_phone_number', 'other_email_address', 'other_fax',
            'court', 'highcourt', 'bench', 'casetype', 'casenumber', 'diarybumber', 'year',
            'court_hall', 'floor', 'title',
            'before_judges', 'referred_by', 'section', 'priority', 'under_acts', 'under_sections',
            'FIR_police_station', 'FIR_number', 'FIR_year',
    ],
    'fallSlip' => [
        'fall_c_name', 'fall_c_gender', 'fall_c_marital_status', 'fall_c_spouse_name',
        'fall_c_emergency_contact_name', 'fall_c_emergency_contact_number', 'fall_c_dob',
        'fall_c_social_security', 'fall_c_address', 'fall_c_phone', 'fall_c_email',
        'fall_c_driver_license', 'fall_c_id',
        'fall_tpi_name', 'fall_tpi_phone', 'fall_tpi_address', 'fall_tpi_email',
        'fall_mi_name', 'fall_mi_phone', 'fall_mi_address', 'fall_mi_email',
         'fall_ii_location_of_incident',
        'fall_ii_address', 'fall_ii_maps_link', 'fall_ii_cause_incident', 'fc_police_department',
        'fc_incident_report',
        'fall_ifp_company_name', 'fall_ifp_insured_name', 'fall_ifp_poilicy',
        'fall_ifp_member', 'fall_ifp_claim', 'fall_ifp_insurance_phone',
        'fall_ifp_adjuster_name', 'fall_ifp_adjuster_email', 'fall_ifp_adjuster_phone',
        'fall_ifp_adjuster_fax', 'fall_ifp_adjuster_policy_limits',
        'fall_itp_company_name', 'fall_itp_insured_name', 'fall_itp_poilicy',
        'fall_itp_claim', 'fall_itp_insurance_phone', 'fall_itp_adjuster_name',
        'fall_itp_adjuster_email', 'fall_itp_adjuster_phone', 'fall_itp_adjuster_fax',
        'fall_itp_adjuster_policy_limits', 'fall_o_incident_report',
        'fall_o_opponent_counsel', 'fall_o_name', 'fall_o_phone', 'fall_o_email',
        'fall_o_fax',
    ],
];